#ifndef CONFIG_H
#define CONFIG_H

#define F_CPU 16000000UL

#define ADC_CHANNEL_TEMPERATURE 0
#define ADC_CHANNEL_LIGHT       1

#define SENSOR_HUMIDITY_PIN_PORT PINB
#define SENSOR_HUMIDITY_PIN_DDR  DDRB
#define SENSOR_HUMIDITY_OUT_PORT PORTB
#define SENSOR_HUMIDITY_PIN      PB0

#define SENSOR_RAIN_PIN_PORT     PINB
#define SENSOR_RAIN_PIN_DDR      DDRB
#define SENSOR_RAIN_OUT_PORT     PORTB
#define SENSOR_RAIN_PIN          PB1

#define COMM_MODE_SELECT_PIN_PORT PIND
#define COMM_MODE_SELECT_PIN_DDR  DDRD
#define COMM_MODE_SELECT_OUT_PORT PORTD
#define COMM_MODE_SELECT_PIN      PD2

#define LOGGER_SAMPLE_DELAY_MS   1000U
#define FILTER_SHIFT             3U
#define STORAGE_MAX_RECORDS      16U

#define COMM_BAUD_RATE           9600UL
#define TWI_FREQUENCY_HZ         100000UL

#define RTC_DS3231_ADDRESS       0x68U
#define RTC_FALLBACK_YEAR        2026U

#endif
